name: ccboard
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  chess_vectors_flutter: ^1.1.0
  chess: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
